name: automl-gpu
channels:
- conda-forge
- anaconda
dependencies:
- python=3.10
- pip=26.0
- numpy~=1.23.5
- pandas~=1.5.3
- py-xgboost=1.7.6
- 'psutil>=5.2.2,<6.0.0'
- tqdm
- setuptools=78.1.1
- wheel=0.46.2
- pip:
  - inference-schema
  - azureml-core
  - azureml-mlflow
  - azureml-defaults
  - azureml-telemetry
  - azureml-interpret
  - azureml-responsibleai
  - azureml-automl-core
  - azureml-automl-runtime
  - azureml-train-automl-client
  - azureml-train-automl-runtime
  - azureml-dataset-runtime
  - azureml-train-automl
  - azureml-contrib-automl-dnn-forecasting
  - https://aka.ms/automl-resources/packages/en_core_web_sm-3.7.1.tar.gz
  - scipy==1.10.1
  - xgboost==1.5.2
  - cmdstanpy==1.0.4
  - spacy==3.7.4
  - prophet==1.1.4
  - GitPython>=3.1.41
  - py-cpuinfo==5.0.0
  - cryptography>=46.0.5
  - distributed>=2026.1.0 
