$schema: https://azuremlschemas.azureedge.net/latest/model.schema.json
name: Phi-3.5-vision-instruct
path: ./
isArchived: true
properties:
  SharedComputeCapacityEnabled: 'True'
  languages: en
  inference-min-sku-spec: 24|1|220|64
  inference-recommended-sku: Standard_NC24ads_A100_v4, Standard_NC48ads_A100_v4,
    Standard_NC96ads_A100_v4, Standard_ND96amsr_A100_v4
tags:
  maas-inference: 'true'
  disable-batch: 'true'
  _aml_system_vanity_registry: azureml-phi
  inference_supported_envs:
  - vllm
  model_specific_defaults:
    apply_deepspeed: 'true'
    deepspeed_stage: 2
    apply_lora: 'true'
    apply_ort: 'false'
    precision: 16
    ignore_mismatched_sizes: 'false'
    num_train_epochs: 1
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 1
    learning_rate: 5e-6
    lr_scheduler_type: cosine
    logging_strategy: steps
    logging_steps: 10
    save_total_limit: 1
system_metadata:
  deploymentOptions:
  - UnifiedEndpointMaaS
  - MaaP
  - ServerlessMaaS
  languages:
  - en
  sharedComputeCapacityEnabled: true
  SKU:
    inferenceRecommendedSkus:
    - Standard_NC24ads_A100_v4
    - Standard_NC48ads_A100_v4
    - Standard_NC96ads_A100_v4
    - Standard_ND96amsr_A100_v4
    inferenceMinSkuSpec: 24|1|220|64
  publisher: Microsoft
  benchmark: quality
  displayName: Phi-3.5-vision instruct (128k)
  evaluation: evaluation.md
  freePlayground: true
  hiddenLayerScanned: true
  inputModalities:
  - text
  - image
  keywords:
  - Multimodal
  - Reasoning
  - Low latency
  license: MIT
  licenseDescription: 'Microsoft.

    Copyright (c) Microsoft Corporation.


    MIT License


    Permission is hereby granted, free of charge, to any person obtaining a copy

    of this software and associated documentation files (the "Software"), to deal

    in the Software without restriction, including without limitation the rights

    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell

    copies of the Software, and to permit persons to whom the Software is

    furnished to do so, subject to the following conditions:


    The above copyright notice and this permission notice shall be included in all

    copies or substantial portions of the Software.


    THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR

    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,

    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE

    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER

    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,

    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE

    SOFTWARE.'
  maxOutputTokens: 4096
  notes: notes.md
  playgroundRateLimitTier: low
  summary: Refresh of Phi-3-vision model.
  textContextWindow: 131072
  trainingDataDate: August 2024
  featured: true
  tasks:
    inferenceTasks:
    - chat-completion
  supportedComputes:
    inferenceComputes:
    - Standard_NC24ads_A100_v4
    - Standard_NC48ads_A100_v4
    - Standard_ND96amsr_A100_v4
    - Standard_NC96ads_A100_v4
  deprecation:
    finetuneDeprecationDate: '2025-06-30T00:00:00.000000Z'
    finetuneRetirementDate: '2025-08-30T00:00:00.000000Z'
    inferenceDeprecationDate: '2025-06-30T00:00:00.000000Z'
    inferenceLegacyDate: '2025-06-09T00:00:00.000000Z'
    inferenceRetirementDate: '2025-08-30T00:00:00.000000Z'
version: 2
description: |
  Phi-3.5-vision is a lightweight, state-of-the-art open multimodal model built upon datasets which include - synthetic data and filtered publicly available websites - with a focus on very high-quality, reasoning dense data both on text and vision. The model belongs to the Phi-3 model family, and the multimodal version comes with 128K context length (in tokens) it can support. The model underwent a rigorous enhancement process, incorporating both supervised fine-tuning and direct preference optimization to ensure precise instruction adherence and robust safety measures.

  ### Resources
  🏡 [Phi-3 Portal](https://azure.microsoft.com/en-us/products/phi-3) <br>
  📰 [Phi-3 Microsoft Blog](https://aka.ms/phi3.5-techblog) <br>
  📖 [Phi-3 Technical Report](https://arxiv.org/abs/2404.14219) <br>
  👩‍🍳 [Phi-3 Cookbook](https://github.com/microsoft/Phi-3CookBook) <br>

  ### Model Summary
  |      |      |
  |------|------|
  | **Architecture** | Phi-3.5-vision has 4.2B parameters and contains image encoder, connector, projector, and Phi-3 Mini language model. |
  | **Inputs** | Text and Image. It’s best suited for prompts using the chat format. |
  | **Context length** | 128K tokens |
  | **GPUs** | 256 A100-80G |
  | **Training time** | 6 days |
  | **Training data** | 500B tokens (vision tokens + text tokens) |
  | **Outputs** | Generated text in response to the input |
  | **Dates** | Trained between July and August 2024 |
  | **Status** | This is a static model trained on an offline text dataset with cutoff date March 15, 2024. Future versions of the tuned models may be released as we improve models. |
  | **Release date** | August 20, 2024 |
  | **License** | MIT |
