name: Clone repository
description: Clone repository
inputs:
  forked-pr:
    description: Whether the event is operating from a forked PR
    required: true
  fetch-depth:
    description: Fetch depth for actions/checkout
    default: "1"

runs:
  using: composite
  steps:
    - name: Clone branch
      if: "!fromJSON(inputs.forked-pr)"
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    
    - name: Clone forked PR
      if: fromJSON(inputs.forked-pr)
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      with:
        ref: refs/pull/${{ github.event.number }}/merge
        fetch-depth: ${{ inputs.fetch-depth }}
    
    - name: Retrieve merge commit hash
      if: fromJSON(inputs.forked-pr)
      shell: bash
      run: echo "merge_commit_hash=$(git log -1 --format='%H')" >> $GITHUB_ENV
