image:
  name: azureml/curated/slime-pytorch-2.9-cuda12.8
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - requirements.txt
  publish:
    location: mcr
    visibility: public
