image:
  name: azureml/curated/automl-gpu
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - conda_dependencies.yaml
    - skops_compatibility_test.py
  publish:
    location: mcr
    visibility: public
