# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Constants."""

COMPONENT_NAME_KEY = "component_name"
COMPONENT_VERSION_KEY = "component_version"
METADATA_JSON_FILENAME = "metadata.json"
OS_ENVIRON_HOST_NAME = "HostName"
OS_ENVIRON_WORKSPACE = "AZUREML_ARM_WORKSPACE_NAME"
OS_ENVIRON_RUN_ID = "AZUREML_RUN_ID"
OS_ENVIRON_NODE_RANK = "AZUREML_CR_NODE_RANK"
OS_ENVIRON_COMPUTE_CONTEXT = "AZUREML_CR_COMPUTE_CONTEXT"
TRAFFIC_GROUP = "batch"

# HTTP request timeout related environment variables
BATCH_SCORE_BACKOFF_FACTOR_REQUEST_TIMEOUT_ENV_VAR = "BATCH_SCORE_BACKOFF_FACTOR_REQUEST_TIMEOUT"
BATCH_SCORE_INITIAL_REQUEST_TIMEOUT_ENV_VAR = "BATCH_SCORE_INITIAL_REQUEST_TIMEOUT"
BATCH_SCORE_MAX_REQUEST_TIMEOUT_ENV_VAR = "BATCH_SCORE_MAX_REQUEST_TIMEOUT"

# Other environment variables
BATCH_SCORE_EMIT_PROMPTS_TO_JOB_LOG_ENV_VAR = "BATCH_SCORE_EMIT_PROMPTS_TO_JOB_LOG"
BATCH_SCORE_NO_DEPLOYMENTS_BACK_OFF_ENV_VAR = "BATCH_SCORE_NO_DEPLOYMENTS_BACK_OFF"
BATCH_SCORE_POLL_DURING_NO_DEPLOYMENTS_ENV_VAR = "BATCH_SCORE_POLL_DURING_NO_DEPLOYMENTS"
BATCH_SCORE_SURFACE_TELEMETRY_EXCEPTIONS_ENV_VAR = "BATCH_SCORE_SURFACE_TELEMETRY_EXCEPTIONS"
BATCH_SCORE_TRACE_LOGGING_ENV_VAR = "BATCH_SCORE_TRACE_LOGGING"

AOAI_ENDPOINT_DOMAIN_SUFFIX_LIST = ["openai.azure.com", "api.cognitive.microsoft.com", "cognitiveservices.azure.com"]
SERVERLESS_ENDPOINT_DOMAIN_SUFFIX = ["inference.ai.azure.com", "models.ai.azure.com"]
NULL_ENDPOINT_DOMAIN_SUFFIX = "null.inference.io"

CONNECTION_AUTH_TYPE = "connection"

IMAGE_URL_CONTENT_TYPE = "image_url"
IMAGE_CONTENT_TYPE = "image"
TEXT_CONTENT_TYPE = "text"

BATCH_SCORE_USER_AGENT = "BatchScoreOss"
