#!/bin/bash

exit_code="$1" # The exit code from nginx
signal="$2"    # The signal which caused nginx to exit (or 0)

echo "`date -uIns` - nginx/finish $@"
echo "`date -uIns` - Exit code $exit_code is not normal. Killing image."

killall runsvdir