name: close-stale-items

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Resolve stale issues
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30
          days-before-issue-close: 7
          days-before-pr-stale: 14
          days-before-pr-close: 7
          stale-issue-message: 'This issue has been marked as stale because it has been inactive for 30 days.'
          close-issue-message: 'This issue has been automatically closed due to inactivity.'
          stale-pr-message: 'This pull request has been marked as stale because it has been inactive for 14 days.'
          close-pr-message: 'This pull request has been automatically closed due to inactivity.'
          operations-per-run: 250
